### ISSUE TITLE
Cli tools are not working anymore with the latest version

### ISSUE THREAD

**Issue by Sozhan308** [IBM/ELM-Python-Client#131]
represt cli commands are not working with the latest version `0.37.1`

`$ represt rm --help
Traceback (most recent call last):
  File "dng/.venv/bin/represt", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "dng/.venv/lib/python3.13/site-packages/elmclient/examples/represt.py", line 392, in main
    represt_main()
    ~~~~~~~~~~~~^^
  File "dng/.venv/lib/python3.13/site-packages/elmclient/examples/represt.py", line 104, in represt_main
    appcls.add_represt_arguments( subparsers, common_args )
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AMApp' has no attribute 'add_represt_arguments'`

**Comment by barny** [comment]
Hi

I haven't tested this with AM at all. In fact alll the Reportable REST functions are little-tested and probably incomplete.

what was the commandline you used?

**Comment by barny** [comment]
Ah I see the problem - in _ccm.py change line 470:
    supports_reportable_rest = True
to:
    supports_reportable_rest = False
